name: Build - Windows

on: [push, pull_request, workflow_dispatch]

jobs:
  mingw-cross:
    runs-on: ubuntu-22.04
    env:
      SDL2DIR: /usr/
      CXX: x86_64-w64-mingw32-g++-posix
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Install dependencies
        run: sudo apt-get update -qq && sudo apt-get install -y
          cmake
          libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev zlib1g-dev
          binutils-mingw-w64-x86-64
          g++-mingw-w64-x86-64-posix
          g++-mingw-w64-x86-64
          libsdl2-mixer-dev
          zlib1g
      - name: Install SDL2
        run: |
          curl -L https://github.com/mmatyas/supermariowar/releases/download/v2.0-beta.0/i686-w64-mingw32_mixerx.tar.xz | tar xJf - -C /tmp/
      - run: |
          $CXX --version
          cmake --version
          mkdir build

      - name: Configure
        working-directory: build
        run: cmake ..
          -DCMAKE_TOOLCHAIN_FILE=../.github/workflows/mingw_toolchain.cmake
          -DUSE_PNG_SAVE=ON
          -DUSE_SDL2_LIBS=ON
          -DSDL2_USE_MIXERX=ON
      - name: Build
        working-directory: build
        run: make

      - name: Package
        run: |
          mkdir supermariowar
          mkdir supermariowar/dll
          cp build/Binaries/Release/{smw,smw-leveledit,smw-worldedit,smw-server}.exe supermariowar/
          cp /usr/lib/gcc/x86_64-w64-mingw32/ supermariowar/dll
          x86_64-w64-mingw32-strip supermariowar/*
          cp docs/readme-v1.8.html supermariowar/
          rsync -aC --exclude .git data supermariowar/
          zip -r "supermariowar_$(date +%F)_windows.zip" supermariowar

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: supermariowar_windows
          path: supermariowar_*_windows.zip
